apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "cpu-mem"
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "2"
        memory: "3Gi"
      min:
        cpu: "1m"
        memory: "1Mi"
    - type: "Container"
      max:
        cpu: "2"
        memory: "3Gi"
      min:
        cpu: "1m"
        memory: "1Mi"
      defaultRequest:
        cpu: "200m"
        memory: "100Mi"
      maxLimitRequestRatio:
        cpu: "100"
