apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 4Gi                                           
